# Generated by Django 5.2.6 on 2025-09-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('شبانه\u200cروزی', 'شبانه\u200cروزی'), ('روزانه', 'روزانه'), ('ساعتی', 'ساعتی')], default='شبانه\u200cروزی', max_length=20)),
                ('ev_charge', models.BooleanField(default=False)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('owner', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='parking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.parking'),
        ),
    ]
