# Generated by Django 5.2.6 on 2025-09-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parking_alter_parkingspot_number_parkingspot_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='password',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='username',
        ),
        migrations.AddField(
            model_name='parking',
            name='owner_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='owner_national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='owner_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='owner_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='column',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='row',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='slot',
            field=models.IntegerField(default=0),
        ),
    ]
