# Generated by Django 5.2.6 on 2025-09-16 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_parking_mobile_remove_parking_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.parking'),
        ),
    ]
