# Generated by Django 5.2.6 on 2025-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2, max_length=15, unique=True, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'راننده'), ('operator', 'اپراتور'), ('admin', 'مدیر')], default='driver', max_length=10, verbose_name='نقش'),
        ),
    ]
