# Generated by Django 5.2.6 on 2025-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_license_plate_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='09123456789', max_length=15, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
